#!/bin/bash

### This script regenerates the packaged html templates, copies any needed files
### (read: config files) to their proper place, and packages the turtl XPI file.
###
### Note that this script is meant to be run in the top-level addon folder, not
### not in the scripts/ folder.

# ------------------------------------------------------------------------------
# config section
# ------------------------------------------------------------------------------
# path to cfx
CFX=`realpath ../../../addon-sdk-1.14/bin/cfx`
# the resulting XPI file (*must* be the same as what cfx xpi produces)
XPI=firefox.xpi

# package the addon
echo "Packaging addon (via cfx)."
$CFX xpi > /dev/null

mv turtl.xpi release/$XPI

echo "Complete. Created fully-packaged file: release/$XPI."

