#!/bin/bash

# temp dir for packaging
TMP=/tmp/turtl-package-chrome
ZIP=release/turtl.zip

rm -rf $TMP/*

echo -n "Copying extension files to temp directory..."
rsync -avk . $TMP/ --exclude="release/" --exclude=".git" --exclude="data/app/.git" > /dev/null
echo "done."

EXTDIR=`realpath .`
mkdir -p $TMP
pushd $TMP/> /dev/null

echo "Packaging extension."

echo -n "Zipping..."
zip -qr -9 -X \
	turtl.crx \
	. \
	-x *.git* \
	-x release/* \
	> /dev/null
echo "done."

mv turtl.crx $EXTDIR/$ZIP || {
	echo "Problem moving $TMP/turtl.crx to $EXTDIR/$ZIP. Exiting."
	exit 1
}
popd > /dev/null

echo "Clearing tmp dir ($TMP/)"
rm -rf $TMP

echo "Complete. Created fully-packaged extension: $ZIP"
