#!/bin/bash

CORE=../../js

cp $CORE/library/tcrypt.js data/
cp $CORE/library/tcrypt.thread.js data/
cp $CORE/library/sjcl.js data/

cp $CORE/images/site/icons/load_16x16.gif data/images
cp $CORE/images/favicon.128.png data/images
cp $CORE/images/favicon.png data/images

# create some firefox/commonjs-specific versions of our libs. yegh.
echo '"use strict";' > data/sjcl.js
echo "var win_util = require('sdk/window/utils');" >> data/sjcl.js
echo "var window = {crypto: win_util.getMostRecentBrowserWindow().crypto};" >> data/sjcl.js
cat data/sjcl.js >> data/sjcl.js
echo '"use strict";' > data/tcrypt.js
echo "var win_util = require('sdk/window/utils');" >> data/tcrypt.js
echo "var window = {crypto: win_util.getMostRecentBrowserWindow().crypto};" >> data/tcrypt.js
echo "var sjcl = require('sjcl');" >> data/tcrypt.js
cat data/tcrypt.js >> data/tcrypt.js
echo "exports.tcrypt = tcrypt;" >> data/tcrypt.js
